import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import Layout from "@theme/Layout";
import {
  SiGithub,
  SiSlack,
  SiDiscord,
  SiNextdotjs,
  SiGoland,
  SiDjango,
  SiPhp,
  SiVuedotjs,
  SiReact,
  SiLaravel,
  SiRust,
} from "react-icons/si";
import { SearchFile, Changelog, Bookmark } from "../../static/img";

import styles from "./index.module.css";

export default function Home() {
  const { siteConfig } = useDocusaurusContext();
  const communities = [
    {
      title: "Discord",
      description: "Join our fast growing community on discord.",
      icon: <SiDiscord />,
      url: "https://discord.gg/wwRSXnJV",
    },
    {
      title: "Slack",
      description: "Join our slack community for support and instant updates.",
      icon: <SiSlack />,
      url: "https://join.slack.com/t/pipeopscommunity/shared_invite/zt-36epz9i8k-p01_WcPQudJmabuF_NqD5Q",
    },
    {
      title: "Github",
      description: "Contribute to our open source documentation on Github",
      icon: <SiGithub />,
      url: "https://github.com/pipeops-dev",
    },
  ];
  const frameworks = [
    {
      title: "React.js",
      icon: <SiReact />,
      link: "/docs/how-to-guides/deployment-templates/deploy-react-template",
    },
    {
      title: "Vue.js",
      icon: <SiVuedotjs />,
      link: "/docs/how-to-guides/deployment-templates/deploy-vuejs-template",
    },
    {
      title: "Next.js",
      icon: <SiNextdotjs />,
      link: "/docs/how-to-guides/deployment-templates/deploy-nextjs-template",
    },
    {
      title: "PHP",
      icon: <SiPhp />,
      link: "/docs/how-to-guides/deployment-templates/deploy-php-template",
    },
    {
      title: "Laravel",
      icon: <SiLaravel />,
      link: "/docs/how-to-guides/deployment-templates/deploy-php-laravel-template",
    },
    {
      title: "Django",
      icon: <SiDjango />,
      link: "/docs/how-to-guides/deployment-templates/deploy-a-django-template",
    },
    {
      title: "Golang",
      icon: <SiGoland />,
      link: "/docs/how-to-guides/deployment-templates/deploy-golang-template",
    },
    {
      title: "Rust",
      icon: <SiRust />,
      link: "/docs/how-to-guides/deployment-templates/deploy-a-rust-template",
    },
  ];

  const getStarted = [
    {
      title: "Overview",
      description:
        "Find out what this documentation is about in a summarized manner.",
      icon: <SearchFile />,
      url: "/docs/overview",
    },
    {
      title: "Guides & Tutorials",
      description:
        "You can get help via our well detailed guides and tutorials",
      icon: <Bookmark />,
      url: "/docs/category/getting-started",
    },
    {
      title: "Changelogs",
      description:
        "See a list of our previous and current versions of changelogs",
      icon: <Changelog />,
      url: "/docs/category/changelogs",
    },
  ];
  return (
    <Layout
      title={`${siteConfig.title} `}
      description="Description will go into a meta tag in <head />"
    >
      <header>
        <h1>PipeOps Documentation</h1>
        <p>
          Welcome to PipeOps Documentation! Empower your projects with our
          innovative no-code platform. Start by creating an account using the
          'getting started & user guides' to learn how to deploy your apps in
          minutes.
        </p>
      </header>
      <main>
        <section>
          <h2>Get Started</h2>
          <div className={styles.cardsWrapper}>
            {getStarted.map(({ title, description, url, icon }, index) => (
              <a href={url} key={title} className={styles.cardVariantTwo}>
                <span>
                  {icon}
                  <img
                    src={
                      index === 0
                        ? "/img/overviewGradient.svg"
                        : index === 1
                          ? "/img/guidesGradient.svg"
                          : "/img/changelogGradient.svg"
                    }
                    alt={title}
                  />
                </span>
                <h3>{title}</h3>
                <p>{description}</p>
              </a>
            ))}
          </div>
          <h2>Some Supported Frameworks</h2>
          <div className={styles.cardsWrapper}>
            {frameworks.map(({ title, icon, link }) => (
              <a href={link} key={title} className={styles.cardVariantThree}>
                <h3>{title}</h3>
                <span>{icon}</span>
              </a>
            ))}
          </div>
          <h2>Community</h2>
          <div className={styles.cardsWrapper}>
            {communities.map(({ title, description, icon, url }) => {
              return (
                <a
                  target="_blank"
                  href={url}
                  key={title}
                  className={styles.card}
                >
                  <span>{icon}</span>
                  <h3>{title}</h3>
                  <p>{description}</p>
                </a>
              );
            })}
          </div>
        </section>
      </main>
    </Layout>
  );
}

const somadServersData = [
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-04-28T21:03:10.756918Z",
      DeletedAt: null,
      uuid: "daa1e3dc-cf88-4cfc-88ba-8db40541a8f9",
      name: "pipeops-joyous-oatmeal",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-joyous-oatmeal",
      buildSha:
        "qsIXaRdYHJtspkbMCcObfBAwvmtYtcgfwRkEqiAJJjTnwIlyBJVQBDWUtsRTROVb",
      cloudProvider: "gcp",
      region: "us-west1",
      gateway_region: "",
      countryCode: "us",
      Package: "e2-medium",
      DeploymentType: "gke",
      vcpu: 2,
      memory: 4294967296,
      storage: 20,
      gpu: false,
      dns: "YyN0Q3JBVXc2JipfPVJZaw==",
      minNode: 1,
      defaultNode: 2,
      maxNode: 5,
      createdAt: "2026-04-27T09:31:53.75184Z",
      clusterEnvironment: "development",
      PrometheusURL:
        "YyN0Q3JBVXc2JipfPVJZa4oYVNlMxQUcZ33jJNXhH88txbB5JUTSj8CknQmlGnbjtpMX09NE",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "General purpose",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: failed to destroy prepare-cluster: failed to create Terraform executor: error initialising Terraform with workdir /app[REDACTED]: stat /app[REDACTED]: no such file or directory",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-joyous-oatmeal Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "aoYTd5hT089e5PPQLztL",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [
        {
          CreatedAt: "2026-04-28T10:34:47.563931Z",
          UpdatedAt: "2026-04-28T10:34:47.563931Z",
          UUID: "c1cbe29f-c022-42b6-9f82-e97917b01dfe",
          Name: "beta",
          NameSlug: "beta-cd773134-684f-4ea8-bad7-34c8543976bb",
          EnvironmentEnvs: null,
          Namespace: "beta",
          ClusterUUID: "daa1e3dc-cf88-4cfc-88ba-8db40541a8f9",
          Clusters: null,
        },
        {
          CreatedAt: "2026-04-28T10:34:47.564009Z",
          UpdatedAt: "2026-04-28T10:34:47.564009Z",
          UUID: "2a1eb422-0d55-40ee-b505-e23889e8d593",
          Name: "production",
          NameSlug: "production-d90f1ebc-7c5d-4e6d-ac7c-6561e339449f",
          EnvironmentEnvs: null,
          Namespace: "production",
          ClusterUUID: "daa1e3dc-cf88-4cfc-88ba-8db40541a8f9",
          Clusters: null,
        },
      ],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl:
        "YyN0Q3JBVXc2JipfPVJZa50YWtID2w1CcnvjMpf7A5vdU8zdHU3DhW85UjY0b8rt1L+n1UU4eiY+",
      OpenCostBaseURL: "YyN0Q3JBVXc2JipfPVJZaw==",
      providerCredentialUUID: "ad701e0d-68a1-4ff8-992d-e8080d723cd8",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 4294967296,
    },
    VCpu: {
      Used: 0,
      Available: 2,
    },
    Storage: {
      Used: 0,
      Available: 20,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-04-24T14:51:57.624316Z",
      DeletedAt: null,
      uuid: "b06519a2-0b7e-49df-b6fd-471528e6dbb1",
      name: "pipeops-vivid-time",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-vivid-time",
      buildSha:
        "HCgxPXpvFmqCRWbflFikviVSWCocbPNmUpSerwHcRovSbtCcIqChrQxdmiBXZtET",
      cloudProvider: "gcp",
      region: "us-west1",
      gateway_region: "",
      countryCode: "us",
      Package: "c2d-highcpu-2",
      DeploymentType: "gke",
      vcpu: 2,
      memory: 4294967296,
      storage: 20,
      gpu: false,
      dns: "",
      minNode: 1,
      defaultNode: 2,
      maxNode: 5,
      createdAt: "2026-04-23T21:44:45.188639Z",
      clusterEnvironment: "development",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to initialize infrastructure configuration.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-vivid-time Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "ISYM1iiftgyGVFDZtwzc",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "ad701e0d-68a1-4ff8-992d-e8080d723cd8",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 4294967296,
    },
    VCpu: {
      Used: 0,
      Available: 2,
    },
    Storage: {
      Used: 0,
      Available: 20,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:11:50.159484Z",
      DeletedAt: null,
      uuid: "93c2cdd2-9a7a-453b-b478-be7c52b71e52",
      name: "pipeops-certain-deer",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-certain-deer",
      buildSha:
        "wilCDyEHKsfAsCMEYhIegVZTeMYTVCyWhtbSPmtNlpjBDfTCsfsjOGMwlXTKvDGj",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-2",
      DeploymentType: "doks",
      vcpu: 2,
      memory: 4294967296,
      storage: 20,
      gpu: false,
      dns: "",
      minNode: 1,
      defaultNode: 2,
      maxNode: 5,
      createdAt: "2026-03-02T16:15:50.753649Z",
      clusterEnvironment: "development",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-certain-deer Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "cRBx6hU5IhvYYk7seR9r",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "ec8718d3-0801-458c-a7fe-a376831438dd",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 4294967296,
    },
    VCpu: {
      Used: 0,
      Available: 2,
    },
    Storage: {
      Used: 0,
      Available: 20,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:10:04.080845Z",
      DeletedAt: null,
      uuid: "5f4660d9-eae3-49c8-a3c8-bcc661d87e37",
      name: "pipeops-foregoing-tomatoes",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-foregoing-tomatoes",
      buildSha:
        "QSuIJhVKLCRynLZzDsGHJCkdVpDdCXotZpigXMfDQCMjklvLAjOZDvyJVCHPxfOu",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-2",
      DeploymentType: "doks",
      vcpu: 2,
      memory: 4294967296,
      storage: 20,
      gpu: false,
      dns: "",
      minNode: 1,
      defaultNode: 2,
      maxNode: 5,
      createdAt: "2026-03-02T16:12:57.102731Z",
      clusterEnvironment: "development",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-foregoing-tomatoes Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "CpzTwv4ruVKs9wTFszpa",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "ec8718d3-0801-458c-a7fe-a376831438dd",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 4294967296,
    },
    VCpu: {
      Used: 0,
      Available: 2,
    },
    Storage: {
      Used: 0,
      Available: 20,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:12:43.367102Z",
      DeletedAt: null,
      uuid: "2a10d0be-5a2f-49b9-a30e-dc0084b61aac",
      name: "pipeops-grateful-destruction",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-grateful-destruction",
      buildSha:
        "EFGCVvcBXoShBoWRHJxkMngNOUpAMfyvYephbYyGdYrRPiWzlMBQXzKbBuBqJKcB",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T14:53:46.097083Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-grateful-destruction Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "ow09AHavTZxGEKGTDa4b",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "e2416ae5-30c1-424f-a794-03222f577554",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:14:25.40981Z",
      DeletedAt: null,
      uuid: "42140826-fe51-42cc-80dd-5b422d58cc9a",
      name: "pipeops-ragged-authority",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-ragged-authority",
      buildSha:
        "IPuPhAZbcyxoIyAAihbsPgvIFayyeWYqsItLuOVOtsMfMZcIQcwwbihYZOjQQSDv",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T14:52:13.152388Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Too many state storage buckets. Please delete unused clusters or contact support.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-ragged-authority Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "W1jKBynaRddO4BME19Ps",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "e2416ae5-30c1-424f-a794-03222f577554",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:10:23.289501Z",
      DeletedAt: null,
      uuid: "ccde7ebc-b887-499a-89c3-a6c5b9aba393",
      name: "pipeops-gorgeous-kiss",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-gorgeous-kiss",
      buildSha:
        "WaLNteJAaFIUYxXdZMDzJwuKXHHaqWCuqMwahNZgizygxwWCiuWTjwtrbGKkqhpb",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T14:45:29.642835Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-gorgeous-kiss Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "HEas3aVQYmp44BBxa1fK",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "779f9329-2d90-4250-84f3-3fa195ffbb33",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:14:51.382178Z",
      DeletedAt: null,
      uuid: "f5884aa3-95bd-4d3a-8417-5e76151517c1",
      name: "pipeops-roasted-crown",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-roasted-crown",
      buildSha:
        "DqHMxBTUGMQDvMhNulAZFBmXuAKXDeWoGppWaXYwQKQLmxjLIWCKxWeUoAFlvKSV",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T14:34:32.284173Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Too many state storage buckets. Please delete unused clusters or contact support.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-roasted-crown Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "02CWMzZrQOI4RrKjdbzk",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "779f9329-2d90-4250-84f3-3fa195ffbb33",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:13:00.936773Z",
      DeletedAt: null,
      uuid: "08b73810-987a-4ff7-8762-2c6dfaab538a",
      name: "pipeops-unusual-mountain",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-unusual-mountain",
      buildSha:
        "UnzqBTJQPFQdhZnPCsnUVEQIIAVnvPqHDwQyQQDhtrIBtuBfqAwYtSqJKpUuUozX",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T14:25:12.657833Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-unusual-mountain Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "wTWd23LPYXQpeKrbnFG3",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "b18b2cad-5030-490a-8092-43fb1e9f4d1b",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-02T16:10:21.082556Z",
      DeletedAt: null,
      uuid: "ab57eecc-9525-4d0f-947b-f5a9450dac08",
      name: "pipeops-chemical-person",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-chemical-person",
      buildSha:
        "rGInocppKwPGajcNaOhfMvsfHHJTZjQTeMBVUHzaBcusmfRDMRUGWtBmPoEpcGSb",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T13:54:00.253414Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-chemical-person Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "RtmzL9BJfBeHENvEXgWt",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "b18b2cad-5030-490a-8092-43fb1e9f4d1b",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:13:31.204718Z",
      DeletedAt: null,
      uuid: "19a757d0-db6f-4f61-9906-8951f5aa8b9c",
      name: "pipeops-nondescript-face",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-nondescript-face",
      buildSha:
        "arTcfcCcDbQongMmnGezauLlBBlajRxaRYiKgBRpbuMRqLexTujoJgweoygXlqxA",
      cloudProvider: "digital_ocean",
      region: "nyc1",
      gateway_region: "",
      countryCode: "us",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T12:05:48.917666Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Failed to create state storage. Please check your DigitalOcean Spaces quota.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-nondescript-face Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "5BHp2rbQRHC91o9Vf3W3",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "00e65511-6a44-4308-b031-98b63f439c82",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:11:19.585806Z",
      DeletedAt: null,
      uuid: "90c3dbbe-162e-4d09-998b-41728d26409f",
      name: "pipeops-perfect-join",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-perfect-join",
      buildSha:
        "lFfXQvUuMMprdsLqQoyQMDdfnwIsEfLaSxskfjDnIsAaMGPHtjqlbKNYTVOwlpmv",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T11:11:44.689575Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Too many state storage buckets. Please delete unused clusters or contact support.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-perfect-join Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "HFe5DvfbToFP98EMvhXx",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "00e65511-6a44-4308-b031-98b63f439c82",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-03-16T07:10:47.747367Z",
      DeletedAt: null,
      uuid: "b877eb33-39ce-4c05-8cb3-3d4fab18c89e",
      name: "pipeops-nonstop-humor",
      WorkspaceName: "pipeops_6bcbf3e8",
      IngressClass: "traefik",
      name_slug: "pipeops-nonstop-humor",
      buildSha:
        "UBUUhggfKsIIahMNTmOjTWjPtmwHGPPOvTxTfxijZkTYjVSmhVurAUJwzciDbCCm",
      cloudProvider: "digital_ocean",
      region: "lon1",
      gateway_region: "",
      countryCode: "gb",
      Package: "c-4",
      DeploymentType: "doks",
      vcpu: 4,
      memory: 8589934592,
      storage: 100,
      gpu: false,
      dns: "",
      minNode: 2,
      defaultNode: 3,
      maxNode: 10,
      createdAt: "2026-03-02T09:01:59.297467Z",
      clusterEnvironment: "production",
      PrometheusURL: "",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "Compute optimized",
      status: "delete_failed",
      Stage:
        "[NOVA Tm] Server Creation Failed: Too many state storage buckets. Please delete unused clusters or contact support.",
      server_code: "",
      ServerType: "",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage:
        "Delete operation failed: pipeops-nonstop-humor Failed during Delete. Please retry deletion.",
      ProjectCount: 0,
      FirestoreRef: "m8xt4MoSVBpTOZAULWSs",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "v1.34",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [],
      SubscriptionID: null,
      providerSlug: "",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "",
      OpenCostBaseURL: "",
      providerCredentialUUID: "00e65511-6a44-4308-b031-98b63f439c82",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 0,
      Available: 8589934592,
    },
    VCpu: {
      Used: 0,
      Available: 4,
    },
    Storage: {
      Used: 0,
      Available: 100,
    },
  },
  {
    Cluster: {
      ID: 0,
      CreatedAt: "0001-01-01T00:00:00Z",
      UpdatedAt: "2026-02-02T13:07:25.614947Z",
      DeletedAt: null,
      uuid: "bddf624d-0702-4bb0-8b51-112cf6ce4a8f",
      name: "creative-utility",
      WorkspaceName: "",
      IngressClass: "traefik",
      name_slug: "creative-utility",
      buildSha:
        "1e629332f0ade5e5ee4f7e304a37af48fe5b8f92306684db66cef4d0fac24968",
      cloudProvider: "pipeops",
      region: "eu-west-2",
      gateway_region: "",
      countryCode: "gb",
      Package: "dev",
      DeploymentType: "pks",
      vcpu: 0,
      memory: 0,
      storage: 0,
      gpu: false,
      dns: "YyN0Q3JBVXc2JipfPVJZa5YFSJlShEIca2L2OIj4XtVYKAl7",
      minNode: 0,
      defaultNode: 0,
      maxNode: 0,
      createdAt: "2026-02-02T13:07:12.167868Z",
      clusterEnvironment: "",
      PrometheusURL: "YyN0Q3JBVXc2JipfPVJZa4oBSJkO2gJdLHP9I4n+EtO/wni3",
      prometheus_service_name: "",
      prometheus_namespace: "",
      prometheus_port: 0,
      InstanceCategory: "",
      status: "available",
      Stage: "Server Now Active",
      server_code: "pks-lon1-gcp-01",
      ServerType: "Growth",
      Cordorned: false,
      StagePercentage: "100%",
      statusMessage: "creative-utility was created successfully",
      ProjectCount: 4,
      FirestoreRef: "QuPBlnw1iLiFBLGJSbVZ",
      APIName: "",
      PrometheusSSL: true,
      ClusterEvent: null,
      cluster_version: "1.34",
      IsGeneric: false,
      IsBilledAfterDeletion: false,
      UpgradeableVersion: "v1.34",
      StableVersion: "1",
      UpgradeAvailable: false,
      team_name: "",
      sharedTeamCluster: false,
      teams: null,
      environments: [
        {
          CreatedAt: "2026-02-02T13:07:25.937862Z",
          UpdatedAt: "2026-02-02T13:07:25.937862Z",
          UUID: "5284e5dd-9a8e-4ff9-858a-302df5ecdd95",
          Name: "creative-utility-production",
          NameSlug:
            "creative-utility-production-2a26e405-51b6-44a3-8aa4-9dec68450ed4",
          EnvironmentEnvs: null,
          Namespace: "creative-utility-production",
          ClusterUUID: "bddf624d-0702-4bb0-8b51-112cf6ce4a8f",
          Clusters: null,
        },
        {
          CreatedAt: "2026-02-02T13:07:25.937933Z",
          UpdatedAt: "2026-02-02T13:07:25.937933Z",
          UUID: "bfe03ef3-55f7-4950-8279-d3628cb39108",
          Name: "creative-utility-beta",
          NameSlug:
            "creative-utility-beta-929e17ef-5d7b-43f5-a62a-8be772ea350f",
          EnvironmentEnvs: null,
          Namespace: "creative-utility-beta",
          ClusterUUID: "bddf624d-0702-4bb0-8b51-112cf6ce4a8f",
          Clusters: null,
        },
      ],
      SubscriptionID: 14948,
      Subscription: {
        UID: "4b0b1141-7e45-4872-bfd1-c0c0722c100a",
        UserUID: "fae03881-5e52-407a-aa2c-fec0ae1b79ff",
        PlanUID: "f2d97c09-c387-4700-81d7-879897b13a7c",
        PlanTier: "growth",
        PlanName: "Growth",
        Quantity: 0,
        PlanNovaUsageDiscount: 5,
        PlanVcpu: 0,
        PlanMemory: 0,
        PlanStorage: 0,
        PlanPeriod: "monthly",
        PartnerCode: "",
        Provider: "stripe",
        Amount: "10.00",
        AmountN: 10,
        AmountUSD: "10.00",
        UnitAmount: "10.00",
        DiscountAmt: "10.00",
        CreditUsed: true,
        BillingScheme: "",
        PaymentMethod: "full_credit",
        ClusterName: "",
        ClusterUID: "",
        BillingType: "paid",
        BillingStatus: "paid",
        CollectionMethod: "",
        Description: "Subscription Payment",
        WorkspaceUID: "55349a32-7f25-4416-beac-2d1101302c65",
        Currency: "USD",
        ManagedServer: "",
        Status: "inactive",
        Date: "0001-01-01T00:00:00Z",
        Permissions: {
          DeployableProjects: {
            Allowed: 9223372036854776000,
            Consumed: 0,
          },
          AutomatedCICD: true,
          EmailChatSupport: true,
          Concurrentbuild: 1,
          AddOns: true,
          WorkspaceCount: {
            Allowed: 9223372036854776000,
            Consumed: 1,
          },
          TeamMembers: {
            Allowed: 0,
            ConsumedValue: 5,
            ToppedUpSeats: 0,
            Consumed: {},
          },
          Environments: {
            Allowed: 5,
            Consumed: 2,
          },
          PipeopsManagedServer: true,
          MonthlyDeployment: {
            Allowed: 235,
            Consumed: 152,
          },
          BYOC: {
            Allowed: 1,
            Consumed: 0,
          },
          Domains: {
            Allowed: 0,
            Consumed: 0,
          },
          AutoSSLRenewal: true,
          AutoScaling: true,
          CustomDomain: true,
          IndustryProvisioningComplianceStandard: true,
          ParallelDeployment: true,
          TerminalAccess: true,
          Observability: true,
          LogRetention: 14,
          ProjectMigration: true,
          ProductSupport: true,
          InDashboardSupportHub: true,
          SlackSupport: true,
          BuildDeployNotification: true,
          MaxVCPU: 4,
          MaxMemory: 8,
          MaxStorage: 100,
          MaxReplica: 2,
        },
        Version: "pasyg",
        InUse: false,
        IsActive: false,
        IsFreeForever: false,
        SubStartDate: "2026-01-05T21:20:56.934106Z",
        SubEndDate: "2026-02-05T21:20:56.934107Z",
        SubEndGracePeriodDate: null,
        PlanCategory: "nova",
        CustomerProvider: null,
        LastNovaUsageBillingDate: "2026-02-07T17:55:23Z",
        LastNovaUsagePaymentDescription: "",
        NovaUsageIdempotencyKey: "",
        HasMaxedOutUsageCredit: false,
        FreeTrialUsageCreditUsed: 0,
        FreeTrialUsageCredit: 5,
        YearlyAmount: 0,
        NextBillingDate: null,
        MonthlyAmount: 0,
        HasSentThresholdIsNearFreeTrialLimitUsageEmail: false,
        HasSentMaxedFreeTrialLimitUsageEmail: false,
        FreezeTimestamp: null,
        GracePeriodReason: "",
        CreatedAt: "2026-01-05T21:20:56.882538Z",
        UpdatedAt: "2026-02-07T17:55:23.861664Z",
        CreatedBy: "user",
      },
      providerSlug: "gcp",
      enableKarpenter: false,
      enableSpotInstances: false,
      defaultNodeArchitecture: "amd64",
      GrafanaUrl: "YyN0Q3JBVXc2JipfPVJZaw==",
      OpenCostBaseURL:
        "YyN0Q3JBVXc2JipfPVJZa5IeT8QRj0NDcnngepTkHoe4Iv7laL0DAiGaxgTnNMxeYxvX71rZe09Lz5Q=",
      providerCredentialUUID: "",
      agent_id: "",
      tunnel_status: "",
      last_heartbeat_at: null,
      k8s_node_count: 0,
      k8s_pod_count: 0,
      cpu_usage: "",
      memory_usage: "",
    },
    Memory: {
      Used: 2251801856311296,
      Available: 0,
    },
    VCpu: {
      Used: 2.5,
      Available: 0,
    },
    Storage: {
      Used: 46116860184273880000,
      Available: 0,
    },
  },
];
